server.port=8080
spring.application.name=lindajamii-api
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
